spring:
#  main:
#    web-application-type: SERVLET

  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello?serverTimezone=UTC
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:trace
