spring:
#  main:
#    web-application-type: SERVLET

  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello?serverTimezone=UTC
    username: root
    password: password
